version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'crate-ci/typos'
  - package-ecosystem: 'cargo'
    directory: '/systemd-container-shell'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 3
