version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'crate-ci/typos'
    groups:
      determinatesystems-actions:
        patterns:
          - 'DeterminateSystems*'
# TODO: Consider to enable this feature after realized CI
# - package-ecosystem: 'docker'
#   directory: '/'
#   schedule:
#     interval: 'monthly'
