FROM ubuntu:24.04@sha256:d4f6f70979d0758d7a6f81e34a61195677f4f4fa576eaf808b79f17499fd93d1

LABEL org.opencontainers.image.source=https://github.com/kachick/containers
LABEL org.opencontainers.image.description="Nix package manager on Ubuntu - systemd"
LABEL org.opencontainers.image.licenses=MIT

# Available versions in apt: https://packages.ubuntu.com/noble/curl
# --no-install-recommends omits ca-certificates
RUN apt-get update \
 && apt-get install --no-install-recommends -y curl=8.5.0-2ubuntu10.4	ca-certificates=20240203 \
 systemd=255.4-1ubuntu8.4 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"

RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
  --extra-conf "sandbox = false" \
  --no-start-daemon \
  --no-confirm

# TODO: Consider to extract from this repository
ARG username="user"
RUN useradd --no-log-init --create-home $username

CMD [ "/bin/systemd", "--system" ]
