FROM public.ecr.aws/ubuntu/ubuntu:24.04_stable@sha256:ca5dac7da0fb8dbad2923608891b6c030586d939d8321443c2199504cc34006f


LABEL org.opencontainers.image.source=https://github.com/kachick/containers
LABEL org.opencontainers.image.description="Nix package manager on Ubuntu - systemd"
LABEL org.opencontainers.image.licenses=MIT

# Available versions in apt: https://packages.ubuntu.com/noble/curl
# --no-install-recommends omits ca-certificates
RUN apt-get update \
 && apt-get install --no-install-recommends -y curl	ca-certificates \
 systemd \
 git \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"

RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
  --extra-conf "sandbox = false" \
  --extra-conf "trusted-users = root user" \
  --extra-conf "accept-flake-config = true" \
  --no-start-daemon \
  --no-confirm

# TODO: Consider to extract from this repository
ARG username="user"
RUN useradd --no-log-init --create-home $username

CMD [ "/bin/systemd", "--system" ]
