name: hadolint
on:
  push:
    branches: [main]
    paths:
      - '**Containerfile'
      - '**.containerfile'
      - '.github/workflows/hadolint.yml'
  pull_request:
    paths:
      - '**Containerfile'
      - '**.containerfile'
      - '.github/workflows/hadolint.yml'

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          recursive: 'true'
          dockerfile: Containerfile
